name: PHPCS check
on:
    pull_request:
        types: [ready_for_review, edited, opened, synchronize]
    # Allow manually triggering the workflow.
    workflow_dispatch:

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    phpcs:
        uses: choctaw-nation/shared-github-actions/.github/workflows/phpcs.yml@main

    final-check:
        needs: [phpcs]
        runs-on: ubuntu-latest
        if: always()
        steps:
            - name: Ensure at least one job passed
              run: |
                  if [[ "${{ needs.phpcs.result }}" == "success" ]]; then
                      echo "Checks passed."
                  else 
                        echo "Checks failed."
                        exit 1
                  fi
